#!/usr/bin/env bash
# PreToolUse(mcp__github__create_pull_request|update_pull_request|issue_write):
# enforce rules/github.md — PR/issue title follows Angular convention, and
# strip AI attribution footers from the body.
set -euo pipefail

input="$(cat)"
title="$(jq -r '.tool_input.title // empty' <<<"$input")"
body="$(jq -r '.tool_input.body // empty' <<<"$input")"

deny() {
  jq -n --arg reason "$1" \
    '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:$reason}}'
  exit 0
}

if [[ -n "$title" ]]; then
  if ! echo "$title" | grep -qE '^(feat|fix|docs|refactor|test|ci|perf): [a-z]'; then
    deny "claude-ops rule: PR/issue title must be 'type: lowercase subject' Angular convention (rules/github.md)."
  fi
  if [[ "$title" == *. ]]; then
    deny "claude-ops rule: PR/issue title must not end with a period (rules/github.md)."
  fi
  if (( ${#title} > 50 )); then
    deny "claude-ops rule: PR/issue title should be <=50 chars like a commit subject, got ${#title} (rules/github.md)."
  fi
fi

if [[ -n "$body" ]]; then
  cleaned="$(printf '%s' "$body" | grep -viE 'co-authored-by:|generated with|generated by|🤖|claude-session:' || true)"
  if [[ "$cleaned" != "$body" ]]; then
    jq -n --arg body "$cleaned" \
      '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"allow",updatedInput:(input | .tool_input * {body:$body})}}' \
      <<<"$input"
    exit 0
  fi
fi

exit 0
